# Generated by Django 4.0.6 on 2022-07-14 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_alter_orderitemsmodel_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitemsmodel',
            name='appoitment',
        ),
    ]
